#!/usr/bin/env python3
"""translate.py — Format diff results into C# ServerConfigDescriptor snippets.

This is scaffolding only: formats new_key entries as C# code stubs with
TODO DisplayName/Description. Real RAG + AI translation plugs in later.
Output has quality-gate markers (# [AUTO]) — human must spot-check before
Injecting into Registry.cs.

Usage:
    python translate.py --core leaves
    python translate.py --all
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DIFFS_DIR = ROOT / "diffs"
KB_DIR = ROOT / "knowledge-base"


# ── Infer value type from default string ──

def infer_type(default: str, key_path: str) -> str:
    d = default.strip()
    if d.lower() in ("true", "false"):
        return "bool"
    if d.startswith("[") or d.startswith("{") or "," in d:
        return "list"
    try:
        float(d)
        return "double" if "." in d else "int"
    except ValueError:
        pass
    # Common enum-ish keys
    enum_hints = ("gamemode", "difficulty", "world", "dimension", "mode", "side",
                  "weather", "time", "policy", "algorithm", "strategy")
    for hint in enum_hints:
        if hint in key_path.lower():
            return "enum"
    return "string"


# ── Query knowledge base (simple exact + fuzzy) ──

def query_knowledge(key_path: str, core_id: str, config_file: str) -> list[dict]:
    """Return up to 3 RAG snippets from knowledge-base/."""
    snippets = []
    # 1. exact core + config file
    kb_core = KB_DIR / core_id
    if kb_core.exists():
        safe_name = config_file.replace("/", "__").replace(".", "_").replace(" ", "_") + ".json"
        for kb_file in kb_core.glob("*.json"):
            try:
                data = json.loads(kb_file.read_text())
            except Exception:
                continue
            for entry in data.get("entries", []):
                if entry["key_path"] == key_path:
                    for ce in entry.get("chinese_entries", []):
                        snippets.append(ce)
            # fuzzy by partial key match
            key_tokens = set(re.split(r"[.\-_]", key_path.lower()))
            for entry in data.get("entries", []):
                if entry["key_path"] == key_path:
                    continue
                entry_tokens = set(re.split(r"[.\-_]", entry["key_path"].lower()))
                if key_tokens & entry_tokens:
                    for ce in entry.get("chinese_entries", []):
                        if ce not in snippets:
                            snippets.append(ce)
    # 2. cross-core fuzzy
    if not snippets:
        for kb_core in KB_DIR.iterdir():
            if not kb_core.is_dir() or kb_core.name == core_id:
                continue
            for kb_file in kb_core.glob("*.json"):
                try:
                    data = json.loads(kb_file.read_text())
                except Exception:
                    continue
                key_tokens = set(re.split(r"[.\-_]", key_path.lower()))
                for entry in data.get("entries", []):
                    entry_tokens = set(re.split(r"[.\-_]", entry["key_path"].lower()))
                    if key_tokens & entry_tokens:
                        for ce in entry.get("chinese_entries", []):
                            if ce not in snippets:
                                snippets.append(ce)
    return snippets[:3]


import re  # noqa


# ── Format one key as C# ServerConfigDescriptor ──

def format_cs(config_file: str, key_path: str, default: str, introduced_in: str | None,
              display_hint: str = "", desc_hint: str = "") -> str:
    vtype = infer_type(default, key_path)
    default_escaped = default.replace("\\", "\\\\").replace("\"", "\\\"")
    default_field = f', DefaultValue = "{default_escaped}"' if default else ""
    introduced = f', IntroducedIn = "{introduced_in}"' if introduced_in else ""
    display_field = f'"{display_hint}"' if display_hint else '"TODO"'
    desc_field = f'"{desc_hint}"' if desc_hint else '"TODO"'
    return (
        f'new ServerConfigDescriptor {{ ConfigFileName = "{config_file}", '
        f'Key = "{key_path}", DisplayName = {display_field}, '
        f'Description = {desc_field}, '
        f'Category = "TODO", ValueType = "{vtype}"'
        f'{default_field}{introduced} }},'
    )


# ── Main ──

def translate_core(core_id: str, diff_path: Path) -> str | None:
    if not diff_path.exists():
        return None
    diff = json.loads(diff_path.read_text())

    lines = [
        f"// ════════════════════════════════════════════════════",
        f"// NEW KEYS — {core_id}",
        f"// Generated by translate.py on {time.strftime('%Y-%m-%d')}",
        f"// ⚠️ QUALITY GATE: Every entry marked # [AUTO] MUST be spot-checked by human.",
        f"//   Use spec Section 3.5 BAD/GOOD example table as your judge.",
        f"//   If ANY entry falls into BAD, re-translate the WHOLE core.",
        f"//   After approval, change # [AUTO] → # [APPROVED] before injecting.",
        f"// ════════════════════════════════════════════════════",
        "",
        "using io.NET.ZTR_OS.Features.ConfigEditor.Services;",
        "",
        "// Injected via tools/core-fetcher/translate.py",
        "",
    ]

    total_new = 0
    spotcheck_records = []  # (config_file, key_path, snippet_index)

    for config_file, cfg in diff.get("configs", {}).items():
        keys = [k for k in cfg["keys"] if k["needs_translation"]]
        if not keys:
            continue
        lines.append(f"// ── {config_file} ({len(keys)} keys) ──")

        for k in keys:
            rag_snippets = query_knowledge(k["path"], core_id, config_file)
            display_hint = desc_hint = ""
            if rag_snippets:
                display_hint = rag_snippets[0]["term"]
                desc_hint = rag_snippets[0]["context"]
            snippet = format_cs(
                config_file, k["path"], k.get("default_latest", ""),
                k.get("introduced_in"), display_hint, desc_hint,
            )
            lines.append(f"{snippet}  # [AUTO] rag_snippets={len(rag_snippets)}")
            spotcheck_records.append({
                "config_file": config_file, "key_path": k["path"],
                "display_hint": display_hint or "(no RAG hit)",
                "state": k["state"], "default": k.get("default_latest", ""),
            })
        lines.append("")
        total_new += len(keys)

    if total_new == 0:
        return None

    # Append spot-check report section
    lines.append("// ════════════════════════════════════════════════════")
    lines.append(f"// SPOT-CHECK REPORT — {total_new} entries need human review")
    lines.append("// Pick 20% random entries. Judge each against BAD/GOOD table in spec.")
    lines.append("// ════════════════════════════════════════════════════")
    lines.append("")
    for r in spotcheck_records:
        lines.append(f"// [{r['state']}] {r['config_file']} :: {r['key_path']}")
        lines.append(f"//   display_hint: {r['display_hint']}")
        lines.append(f"//   default:      {r['default']}")
        lines.append("")

    return "\n".join(lines), total_new


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--core")
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()

    if args.all:
        diff_files = sorted(DIFFS_DIR.glob("*.diff.json"))
    elif args.core:
        f = DIFFS_DIR / f"{args.core}.diff.json"
        diff_files = [f]
    else:
        print("Need --core or --all")
        return

    for df in diff_files:
        core_id = df.stem.replace(".diff", "")
        result = translate_core(core_id, df)
        if result is None:
            print(f"[{core_id}] no new keys")
            continue
        content, count = result
        out = df.with_name(f"{core_id}.new-keys.snippets.cs")
        out.write_text(content)
        print(f"[{core_id}] {count} entries → {out.name}")
        print(f"  QUALITY GATE: must spot-check 20% → change [AUTO] to [APPROVED] after approval")


if __name__ == "__main__":
    main()
