// ════════════════════════════════════════════════════
// NEW KEYS — akarin
// Generated by translate.py on 2026-09-02
// ⚠️ QUALITY GATE: Every entry marked # [AUTO] MUST be spot-checked by human.
//   Use spec Section 3.5 BAD/GOOD example table as your judge.
//   If ANY entry falls into BAD, re-translate the WHOLE core.
//   After approval, change # [AUTO] → # [APPROVED] before injecting.
// ════════════════════════════════════════════════════

using io.NET.ZTR_OS.Features.ConfigEditor.Services;

// Injected via tools/core-fetcher/translate.py

// ── akarin.yml (32 keys) ──
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.allow-spawner-modify", DisplayName = "允许旧版客户端", Description = "是否允许低于后端子服版本的 Java 客户端通过协议转换进入。true=开启跨版本；false=严格匹配版本", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.disable-end-portal-create", DisplayName = "禁用活塞物理", Description = "是否禁用活塞推拉方块时的物理计算。true=活塞推方块不再触发物理（极省 CPU 但破坏红石机器）；false=原版行为", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.force-difficulty-on-hardcore", DisplayName = "禁用攻击打断冲刺", Description = "是否禁用攻击时打断冲刺（1.8 PVP 手感）。", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.gc-before-stuck-restart", DisplayName = "崩溃自动重启", Description = "服务器崩溃时是否自动执行 restart-script。", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.legacy-versioning-compat", DisplayName = "兼容模式", Description = "是否启用 NPC 插件兼容模式。若使用 Citizens 等基于实体的 NPC 插件建议开启（性能略降）；若使用基于数据包的 NPC 插件可关闭以获得更好性能。", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.modified-server-brand-name", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "string", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "alternative.version-update-interval", DisplayName = "配置版本号", Description = "内部使用，**不要手动修改**。Akarin 用它做配置自动升级与兼容性判断。", Category = "TODO", ValueType = "string", DefaultValue = "3600s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "bootstrap.extra-local-address", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "list", DefaultValue = "[]", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.always-silent-async-timing", DisplayName = "异步方块物理", Description = "是否异步处理方块物理（沙子掉落、水流等）。true=移出主线程，可省 TPS；false=原版同步。⚠️ 异步可能与某些依赖物理事件的插件冲突", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.chunk-save-threads", DisplayName = "物理线程数", Description = "物理多线程使用的线程数。0=自动（按 CPU 核心数估算）；正值=固定值。建议 ≤ 物理核心数，避免线程切换开销", Category = "TODO", ValueType = "int", DefaultValue = "2", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.enable-panda-redstone-wire", DisplayName = "启用多线程物理", Description = "Akarin 招牌开关。true=启用物理多线程，把区块 ticking 分摊到多核；false=退化为单线程 Paper。⚠️ 关闭后 Akarin 与普通 Paper 无差异，建议保持 true", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.enable-real-time-ticking", DisplayName = "启用多线程物理", Description = "Akarin 招牌开关。true=启用物理多线程，把区块 ticking 分摊到多核；false=退化为单线程 Paper。⚠️ 关闭后 Akarin 与普通 Paper 无差异，建议保持 true", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.keep-alive-response-timeout", DisplayName = "聊天线程核心数", Description = "处理玩家聊天的核心线程数。", Category = "TODO", ValueType = "enum", DefaultValue = "30s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.optimize-chunk-unloading", DisplayName = "优化实体传送门", Description = "是否优化实体穿越传送门（下界/末地）的处理逻辑。开启可减少传送门附近的卡顿。", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.parallel-mode", DisplayName = "聊天线程核心数", Description = "处理玩家聊天的核心线程数。", Category = "TODO", ValueType = "int", DefaultValue = "1", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.players-per-chunk-io-thread", DisplayName = "启用多线程物理", Description = "Akarin 招牌开关。true=启用物理多线程，把区块 ticking 分摊到多核；false=退化为单线程 Paper。⚠️ 关闭后 Akarin 与普通 Paper 无差异，建议保持 true", Category = "TODO", ValueType = "int", DefaultValue = "50", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.primary-thread-priority", DisplayName = "启用多线程物理", Description = "Akarin 招牌开关。true=启用物理多线程，把区块 ticking 分摊到多核；false=退化为单线程 Paper。⚠️ 关闭后 Akarin 与普通 Paper 无差异，建议保持 true", Category = "TODO", ValueType = "int", DefaultValue = "7", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.send-light-only-chunk-sections", DisplayName = "基础加载器区块上限", Description = "单个玩家每 tick 最多生成 / 加载多少区块。降低可缓解玩家快速移动（鞘翅）时的卡顿。", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.thread-safe.async-catcher.throw-on-caught", DisplayName = "启用多线程物理", Description = "Akarin 招牌开关。true=启用物理多线程，把区块 ticking 分摊到多核；false=退化为单线程 Paper。⚠️ 关闭后 Akarin 与普通 Paper 无差异，建议保持 true", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.tick-rate.keep-alive-packet-send-interval", DisplayName = "异步 tick 模式", Description = "实验性：是否启用异步 tick 模式（部分世界逻辑异步执行）。⚠️ 极不稳定，与绝大多数 Forge 模组冲突，**强烈不建议开启**。", Category = "TODO", ValueType = "string", DefaultValue = "15s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.tick-rate.players-info-update-interval", DisplayName = "异步 tick 模式", Description = "实验性：是否启用异步 tick 模式（部分世界逻辑异步执行）。⚠️ 极不稳定，与绝大多数 Forge 模组冲突，**强烈不建议开启**。", Category = "TODO", ValueType = "string", DefaultValue = "30s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "core.tick-rate.world-time-update-interval", DisplayName = "异步方块物理", Description = "是否异步处理方块物理（沙子掉落、水流等）。true=移出主线程，可省 TPS；false=原版同步。⚠️ 异步可能与某些依赖物理事件的插件冲突", Category = "TODO", ValueType = "enum", DefaultValue = "1s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.connect.player-join-server", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "§e%s joined the game", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.connect.renamed-player-join-server", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "§e%s (formerly known as %s) joined the game", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.ban-expires", DisplayName = "白名单提示", Description = "非白名单玩家加入时显示的提示。支持 § 颜色码。", Category = "TODO", ValueType = "string", DefaultValue = "
Your ban will be removed on ", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.ban-player-ip", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "Your IP address is banned from this server! %s %s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.ban-player-name", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "string", DefaultValue = "You are banned from this server! %s %s", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.ban-reason", DisplayName = "白名单提示", Description = "非白名单玩家加入时显示的提示。支持 § 颜色码。", Category = "TODO", ValueType = "string", DefaultValue = "
Reason: ", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.kick-player", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "Kicked by an operator.", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.kick-player-duplicate-login", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "You logged in from another location", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.kick-player-timeout-keep-alive", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "enum", DefaultValue = "Timed out", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "akarin.yml", Key = "messages.disconnect.player-quit-server", DisplayName = "玩家区块加载速率", Description = "单个玩家每秒最多加载多少区块。-1 无限制。降低可保护 CPU。", Category = "TODO", ValueType = "string", DefaultValue = "§e%s left the game", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3

// ── spigot.yml (61 keys) ──
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "advancements.disable-saving", DisplayName = "禁用活塞物理", Description = "是否禁用活塞推拉方块时的物理计算。true=活塞推方块不再触发物理（极省 CPU 但破坏红石机器）；false=原版行为", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "advancements.disabled", DisplayName = "禁用成就保存", Description = "是否禁用玩家成就进度保存。⚠️ 关闭后玩家成就不持久化。", Category = "TODO", ValueType = "list", DefaultValue = "[\"minecraft:story/disabled\"]", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "commands.log", DisplayName = "启用 /version 命令", Description = "是否允许玩家使用 /version（/ver）查看服务端版本。⚠️ 推断项。公网服建议关闭以防信息泄露。", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "commands.replace-commands", DisplayName = "启用 /version 命令", Description = "是否允许玩家使用 /version（/ver）查看服务端版本。⚠️ 推断项。公网服建议关闭以防信息泄露。", Category = "TODO", ValueType = "list", DefaultValue = "[\"setblock\", \"summon\", \"testforblock\", \"tellraw\"]", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "commands.silent-commandblock-console", DisplayName = "启用 /version 命令", Description = "是否允许玩家使用 /version（/ver）查看服务端版本。⚠️ 推断项。公网服建议关闭以防信息泄露。", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "commands.spam-exclusions", DisplayName = "启用 /version 命令", Description = "是否允许玩家使用 /version（/ver）查看服务端版本。⚠️ 推断项。公网服建议关闭以防信息泄露。", Category = "TODO", ValueType = "list", DefaultValue = "[\"/skill\"]", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "config-version", DisplayName = "配置版本号", Description = "内部使用，**不要手动修改**。Akarin 用它做配置自动升级与兼容性判断。", Category = "TODO", ValueType = "int", DefaultValue = "11", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.outdated-client", DisplayName = "白名单提示", Description = "非白名单玩家加入时显示的提示。支持 § 颜色码。", Category = "TODO", ValueType = "string", DefaultValue = "Outdated client! Please use {0}", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.outdated-server", DisplayName = "服务器活跃统计单位", Description = "服务器活跃统计的时间单位。", Category = "TODO", ValueType = "string", DefaultValue = "Outdated server! I'm still on {0}", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.restart", DisplayName = "崩溃自动重启", Description = "服务器崩溃时是否自动执行 restart-script。", Category = "TODO", ValueType = "string", DefaultValue = "Server is restarting", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.server-full", DisplayName = "服务器活跃统计单位", Description = "服务器活跃统计的时间单位。", Category = "TODO", ValueType = "string", DefaultValue = "The server is full!", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.unknown-command", DisplayName = "启用 /version 命令", Description = "是否允许玩家使用 /version（/ver）查看服务端版本。⚠️ 推断项。公网服建议关闭以防信息泄露。", Category = "TODO", ValueType = "string", DefaultValue = "Unknown command. Type \"/help\" for help.", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "messages.whitelist", DisplayName = "白名单提示", Description = "非白名单玩家加入时显示的提示。支持 § 颜色码。", Category = "TODO", ValueType = "string", DefaultValue = "You are not whitelisted on this server!", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.attribute.attackDamage.max", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "2048.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.attribute.maxHealth.max", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "2048.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.attribute.movementSpeed.max", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "2048.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.filter-creative-items", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.int-cache-limit", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "1024", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.item-dirty-ticks", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "20", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.late-bind", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.moved-too-quickly-multiplier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "10.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.moved-wrongly-threshold", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.0625", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "settings.save-user-cache-on-stop-only", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "stats.disable-saving", DisplayName = "禁用活塞物理", Description = "是否禁用活塞推拉方块时的物理计算。true=活塞推方块不再触发物理（极省 CPU 但破坏红石机器）；false=原版行为", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-activation-range.animals", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "32", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-activation-range.misc", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "16", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-activation-range.monsters", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "32", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-activation-range.tick-inactive-villagers", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-activation-range.water", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "16", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-tracking-range.animals", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "48", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-tracking-range.misc", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "32", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-tracking-range.monsters", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "48", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-tracking-range.other", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "64", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.entity-tracking-range.players", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "48", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.cactus-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.cane-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.cocoa-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.melon-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.mushroom-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.netherwart-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.pumpkin-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.sapling-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.vine-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.growth.wheat-modifier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hopper-amount", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "1", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.combat-exhaustion", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.jump-sprint-exhaustion", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.jump-walk-exhaustion", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.05", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.other-multiplier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.regen-exhaustion", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "6.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.sprint-multiplier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.hunger.swim-multiplier", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "0.01", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.item-despawn-rate", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "6000", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.max-tick-time.entity", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "50", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.max-tick-time.tile", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "50", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.max-tnt-per-tick", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "100", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.merge-radius.exp", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "3.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.squid-spawn-range.min", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "double", DefaultValue = "45.0", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.ticks-per.hopper-check", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "1", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.ticks-per.hopper-transfer", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "int", DefaultValue = "8", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "spigot.yml", Key = "world-settings.default.verbose", DisplayName = "服务端品牌名", Description = "发送给客户端的服务端品牌名（F3 界面 "Mod" 字段）。可用 § 颜色码，可隐藏真实核心类型", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "1.12.2-R0.4.4" },  # [AUTO] rag_snippets=3

// ════════════════════════════════════════════════════
// SPOT-CHECK REPORT — 93 entries need human review
// Pick 20% random entries. Judge each against BAD/GOOD table in spec.
// ════════════════════════════════════════════════════

// [new_key] akarin.yml :: alternative.allow-spawner-modify
//   display_hint: 允许旧版客户端
//   default:      True

// [new_key] akarin.yml :: alternative.disable-end-portal-create
//   display_hint: 禁用活塞物理
//   default:      False

// [new_key] akarin.yml :: alternative.force-difficulty-on-hardcore
//   display_hint: 禁用攻击打断冲刺
//   default:      True

// [new_key] akarin.yml :: alternative.gc-before-stuck-restart
//   display_hint: 崩溃自动重启
//   default:      True

// [new_key] akarin.yml :: alternative.legacy-versioning-compat
//   display_hint: 兼容模式
//   default:      False

// [new_key] akarin.yml :: alternative.modified-server-brand-name
//   display_hint: 服务端品牌名
//   default:      

// [new_key] akarin.yml :: alternative.version-update-interval
//   display_hint: 配置版本号
//   default:      3600s

// [new_key] akarin.yml :: bootstrap.extra-local-address
//   display_hint: (no RAG hit)
//   default:      []

// [new_key] akarin.yml :: core.always-silent-async-timing
//   display_hint: 异步方块物理
//   default:      False

// [new_key] akarin.yml :: core.chunk-save-threads
//   display_hint: 物理线程数
//   default:      2

// [new_key] akarin.yml :: core.enable-panda-redstone-wire
//   display_hint: 启用多线程物理
//   default:      False

// [new_key] akarin.yml :: core.enable-real-time-ticking
//   display_hint: 启用多线程物理
//   default:      True

// [new_key] akarin.yml :: core.keep-alive-response-timeout
//   display_hint: 聊天线程核心数
//   default:      30s

// [new_key] akarin.yml :: core.optimize-chunk-unloading
//   display_hint: 优化实体传送门
//   default:      False

// [new_key] akarin.yml :: core.parallel-mode
//   display_hint: 聊天线程核心数
//   default:      1

// [new_key] akarin.yml :: core.players-per-chunk-io-thread
//   display_hint: 启用多线程物理
//   default:      50

// [new_key] akarin.yml :: core.primary-thread-priority
//   display_hint: 启用多线程物理
//   default:      7

// [new_key] akarin.yml :: core.send-light-only-chunk-sections
//   display_hint: 基础加载器区块上限
//   default:      True

// [new_key] akarin.yml :: core.thread-safe.async-catcher.throw-on-caught
//   display_hint: 启用多线程物理
//   default:      True

// [new_key] akarin.yml :: core.tick-rate.keep-alive-packet-send-interval
//   display_hint: 异步 tick 模式
//   default:      15s

// [new_key] akarin.yml :: core.tick-rate.players-info-update-interval
//   display_hint: 异步 tick 模式
//   default:      30s

// [new_key] akarin.yml :: core.tick-rate.world-time-update-interval
//   display_hint: 异步方块物理
//   default:      1s

// [new_key] akarin.yml :: messages.connect.player-join-server
//   display_hint: 玩家区块加载速率
//   default:      §e%s joined the game

// [new_key] akarin.yml :: messages.connect.renamed-player-join-server
//   display_hint: 玩家区块加载速率
//   default:      §e%s (formerly known as %s) joined the game

// [new_key] akarin.yml :: messages.disconnect.ban-expires
//   display_hint: 白名单提示
//   default:      
Your ban will be removed on 

// [new_key] akarin.yml :: messages.disconnect.ban-player-ip
//   display_hint: 玩家区块加载速率
//   default:      Your IP address is banned from this server! %s %s

// [new_key] akarin.yml :: messages.disconnect.ban-player-name
//   display_hint: 服务端品牌名
//   default:      You are banned from this server! %s %s

// [new_key] akarin.yml :: messages.disconnect.ban-reason
//   display_hint: 白名单提示
//   default:      
Reason: 

// [new_key] akarin.yml :: messages.disconnect.kick-player
//   display_hint: 玩家区块加载速率
//   default:      Kicked by an operator.

// [new_key] akarin.yml :: messages.disconnect.kick-player-duplicate-login
//   display_hint: 玩家区块加载速率
//   default:      You logged in from another location

// [new_key] akarin.yml :: messages.disconnect.kick-player-timeout-keep-alive
//   display_hint: 玩家区块加载速率
//   default:      Timed out

// [new_key] akarin.yml :: messages.disconnect.player-quit-server
//   display_hint: 玩家区块加载速率
//   default:      §e%s left the game

// [new_key] spigot.yml :: advancements.disable-saving
//   display_hint: 禁用活塞物理
//   default:      False

// [new_key] spigot.yml :: advancements.disabled
//   display_hint: 禁用成就保存
//   default:      ["minecraft:story/disabled"]

// [new_key] spigot.yml :: commands.log
//   display_hint: 启用 /version 命令
//   default:      True

// [new_key] spigot.yml :: commands.replace-commands
//   display_hint: 启用 /version 命令
//   default:      ["setblock", "summon", "testforblock", "tellraw"]

// [new_key] spigot.yml :: commands.silent-commandblock-console
//   display_hint: 启用 /version 命令
//   default:      False

// [new_key] spigot.yml :: commands.spam-exclusions
//   display_hint: 启用 /version 命令
//   default:      ["/skill"]

// [new_key] spigot.yml :: config-version
//   display_hint: 配置版本号
//   default:      11

// [new_key] spigot.yml :: messages.outdated-client
//   display_hint: 白名单提示
//   default:      Outdated client! Please use {0}

// [new_key] spigot.yml :: messages.outdated-server
//   display_hint: 服务器活跃统计单位
//   default:      Outdated server! I'm still on {0}

// [new_key] spigot.yml :: messages.restart
//   display_hint: 崩溃自动重启
//   default:      Server is restarting

// [new_key] spigot.yml :: messages.server-full
//   display_hint: 服务器活跃统计单位
//   default:      The server is full!

// [new_key] spigot.yml :: messages.unknown-command
//   display_hint: 启用 /version 命令
//   default:      Unknown command. Type "/help" for help.

// [new_key] spigot.yml :: messages.whitelist
//   display_hint: 白名单提示
//   default:      You are not whitelisted on this server!

// [new_key] spigot.yml :: settings.attribute.attackDamage.max
//   display_hint: 服务端品牌名
//   default:      2048.0

// [new_key] spigot.yml :: settings.attribute.maxHealth.max
//   display_hint: 服务端品牌名
//   default:      2048.0

// [new_key] spigot.yml :: settings.attribute.movementSpeed.max
//   display_hint: 服务端品牌名
//   default:      2048.0

// [new_key] spigot.yml :: settings.filter-creative-items
//   display_hint: 服务端品牌名
//   default:      True

// [new_key] spigot.yml :: settings.int-cache-limit
//   display_hint: 服务端品牌名
//   default:      1024

// [new_key] spigot.yml :: settings.item-dirty-ticks
//   display_hint: 服务端品牌名
//   default:      20

// [new_key] spigot.yml :: settings.late-bind
//   display_hint: 服务端品牌名
//   default:      False

// [new_key] spigot.yml :: settings.moved-too-quickly-multiplier
//   display_hint: 服务端品牌名
//   default:      10.0

// [new_key] spigot.yml :: settings.moved-wrongly-threshold
//   display_hint: 服务端品牌名
//   default:      0.0625

// [new_key] spigot.yml :: settings.save-user-cache-on-stop-only
//   display_hint: 服务端品牌名
//   default:      False

// [new_key] spigot.yml :: stats.disable-saving
//   display_hint: 禁用活塞物理
//   default:      False

// [new_key] spigot.yml :: world-settings.default.entity-activation-range.animals
//   display_hint: 服务端品牌名
//   default:      32

// [new_key] spigot.yml :: world-settings.default.entity-activation-range.misc
//   display_hint: 服务端品牌名
//   default:      16

// [new_key] spigot.yml :: world-settings.default.entity-activation-range.monsters
//   display_hint: 服务端品牌名
//   default:      32

// [new_key] spigot.yml :: world-settings.default.entity-activation-range.tick-inactive-villagers
//   display_hint: 服务端品牌名
//   default:      True

// [new_key] spigot.yml :: world-settings.default.entity-activation-range.water
//   display_hint: 服务端品牌名
//   default:      16

// [new_key] spigot.yml :: world-settings.default.entity-tracking-range.animals
//   display_hint: 服务端品牌名
//   default:      48

// [new_key] spigot.yml :: world-settings.default.entity-tracking-range.misc
//   display_hint: 服务端品牌名
//   default:      32

// [new_key] spigot.yml :: world-settings.default.entity-tracking-range.monsters
//   display_hint: 服务端品牌名
//   default:      48

// [new_key] spigot.yml :: world-settings.default.entity-tracking-range.other
//   display_hint: 服务端品牌名
//   default:      64

// [new_key] spigot.yml :: world-settings.default.entity-tracking-range.players
//   display_hint: 服务端品牌名
//   default:      48

// [new_key] spigot.yml :: world-settings.default.growth.cactus-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.cane-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.cocoa-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.melon-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.mushroom-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.netherwart-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.pumpkin-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.sapling-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.vine-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.growth.wheat-modifier
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.hopper-amount
//   display_hint: 服务端品牌名
//   default:      1

// [new_key] spigot.yml :: world-settings.default.hunger.combat-exhaustion
//   display_hint: 服务端品牌名
//   default:      0.1

// [new_key] spigot.yml :: world-settings.default.hunger.jump-sprint-exhaustion
//   display_hint: 服务端品牌名
//   default:      0.2

// [new_key] spigot.yml :: world-settings.default.hunger.jump-walk-exhaustion
//   display_hint: 服务端品牌名
//   default:      0.05

// [new_key] spigot.yml :: world-settings.default.hunger.other-multiplier
//   display_hint: 服务端品牌名
//   default:      0.0

// [new_key] spigot.yml :: world-settings.default.hunger.regen-exhaustion
//   display_hint: 服务端品牌名
//   default:      6.0

// [new_key] spigot.yml :: world-settings.default.hunger.sprint-multiplier
//   display_hint: 服务端品牌名
//   default:      0.1

// [new_key] spigot.yml :: world-settings.default.hunger.swim-multiplier
//   display_hint: 服务端品牌名
//   default:      0.01

// [new_key] spigot.yml :: world-settings.default.item-despawn-rate
//   display_hint: 服务端品牌名
//   default:      6000

// [new_key] spigot.yml :: world-settings.default.max-tick-time.entity
//   display_hint: 服务端品牌名
//   default:      50

// [new_key] spigot.yml :: world-settings.default.max-tick-time.tile
//   display_hint: 服务端品牌名
//   default:      50

// [new_key] spigot.yml :: world-settings.default.max-tnt-per-tick
//   display_hint: 服务端品牌名
//   default:      100

// [new_key] spigot.yml :: world-settings.default.merge-radius.exp
//   display_hint: 服务端品牌名
//   default:      3.0

// [new_key] spigot.yml :: world-settings.default.squid-spawn-range.min
//   display_hint: 服务端品牌名
//   default:      45.0

// [new_key] spigot.yml :: world-settings.default.ticks-per.hopper-check
//   display_hint: 服务端品牌名
//   default:      1

// [new_key] spigot.yml :: world-settings.default.ticks-per.hopper-transfer
//   display_hint: 服务端品牌名
//   default:      8

// [new_key] spigot.yml :: world-settings.default.verbose
//   display_hint: 服务端品牌名
//   default:      True
