// ════════════════════════════════════════════════════
// NEW KEYS — glowstone
// Generated by translate.py on 2026-09-02
// ⚠️ QUALITY GATE: Every entry marked # [AUTO] MUST be spot-checked by human.
//   Use spec Section 3.5 BAD/GOOD example table as your judge.
//   If ANY entry falls into BAD, re-translate the WHOLE core.
//   After approval, change # [AUTO] → # [APPROVED] before injecting.
// ════════════════════════════════════════════════════

using io.NET.ZTR_OS.Features.ConfigEditor.Services;

// Injected via tools/core-fetcher/translate.py

// ── glowstone.yml (83 keys) ──
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.compression-threshold", DisplayName = "网络压缩阈值", Description = "数据包字节数大于该值才压缩；-1=禁用压缩；0=全部压缩", Category = "TODO", ValueType = "int", DefaultValue = "256", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.connection-throttle", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "int", DefaultValue = "4000", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.deprecated-verbose", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "bool", DefaultValue = "false", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.exact-login-location", DisplayName = "精确登录位置", Description = "玩家上线时是否精确还原离线时位置", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.graphics-compute.enable", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.graphics-compute.use-any-device", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.idle-timeout", DisplayName = "空闲超时", Description = "玩家无操作多少分钟后踢出，0=禁用", Category = "TODO", ValueType = "int", DefaultValue = "0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.player-sample-count", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "int", DefaultValue = "12", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.plugin-profiling", DisplayName = "插件性能分析", Description = "启用 /timings 命令分析插件性能", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.profile-lookup-timeout", DisplayName = "连接节流", Description = "同一玩家两次连接的最小间隔（毫秒），防刷屏", Category = "TODO", ValueType = "int", DefaultValue = "5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.proxy-support", DisplayName = "拒绝代理连接", Description = "启用后逐个反向解析玩家 IP 防止代理，可能误伤，建议关闭", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.region-file.cache-size", DisplayName = "日志文件路径", Description = "主日志输出文件", Category = "TODO", ValueType = "int", DefaultValue = "256", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.region-file.compression", DisplayName = "日志文件路径", Description = "主日志输出文件", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.suggest-player-name-when-null-tab-completions", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "advanced.warn-on-overload", DisplayName = "过载警告", Description = "服务器 tick 超时时是否在控制台输出警告", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "console.date-format", DisplayName = "日期格式", Description = "日志时间戳格式，遵循 Java SimpleDateFormat 语法", Category = "TODO", ValueType = "string", DefaultValue = "HH:mm:ss", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "console.log-date-format", DisplayName = "日志文件路径", Description = "主日志输出文件", Category = "TODO", ValueType = "string", DefaultValue = "yyyy/MM/dd HH:mm:ss", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "console.prompt", DisplayName = "资源包提示文本", Description = "推送资源包时弹窗显示的提示文字", Category = "TODO", ValueType = "string", DefaultValue = "> ", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "console.use-jline", DisplayName = "启用命令历史", Description = "控制台支持上下方向键翻阅历史命令", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.enable.animals", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.enable.monsters", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.enable.npcs", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.limit.ambient", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "15", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.limit.animals", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "15", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.limit.monsters", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "70", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.limit.water", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.ticks.animal", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "400", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "creatures.ticks.monsters", DisplayName = "生成怪物", Description = "是否生成敌对怪物", Category = "TODO", ValueType = "int", DefaultValue = "1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.query-enabled", DisplayName = "启用信息收集", Description = "上报匿名数据到 Mojang，强烈建议保持 false", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.query-plugins", DisplayName = "插件目录", Description = "Bukkit 插件 jar 放置目录", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.query-port", DisplayName = "服务器端口", Description = "客户端连接端口，0 表示随机端口", Category = "TODO", ValueType = "int", DefaultValue = "25614", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.rcon-colors", DisplayName = "控制台彩色输出", Description = "日志按级别上色，Windows 旧 cmd 可能显示乱码", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.rcon-enabled", DisplayName = "启用信息收集", Description = "上报匿名数据到 Mojang，强烈建议保持 false", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.rcon-password", DisplayName = "显示 TPS", Description = "在控制台定时输出当前 TPS", Category = "TODO", ValueType = "string", DefaultValue = "glowstone", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "extras.rcon-port", DisplayName = "服务器端口", Description = "客户端连接端口，0 表示随机端口", Category = "TODO", ValueType = "int", DefaultValue = "25575", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "files.commands", DisplayName = "命令文件", Description = "命令别名配置文件名", Category = "TODO", ValueType = "string", DefaultValue = "commands.yml", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "files.help", DisplayName = "帮助文件", Description = "帮助主题配置文件名", Category = "TODO", ValueType = "string", DefaultValue = "help.yml", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "files.permissions", DisplayName = "权限文件", Description = "默认权限配置文件名", Category = "TODO", ValueType = "string", DefaultValue = "permissions.yml", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "folders.libraries", DisplayName = "配置目录", Description = "所有 YAML 配置所在目录", Category = "TODO", ValueType = "string", DefaultValue = "lib", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "folders.plugins", DisplayName = "插件目录", Description = "Bukkit 插件 jar 放置目录", Category = "TODO", ValueType = "string", DefaultValue = "plugins", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "folders.update", DisplayName = "配置目录", Description = "所有 YAML 配置所在目录", Category = "TODO", ValueType = "string", DefaultValue = "update", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "folders.worlds", DisplayName = "世界目录", Description = "世界存档数据目录", Category = "TODO", ValueType = "enum", DefaultValue = "worlds", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.allow-flight", DisplayName = "允许飞行", Description = "非创造模式是否允许飞行（防作弊检测）", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.announce-achievements", DisplayName = "公告成就", Description = "玩家获得成就时是否全服广播", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.command-blocks", DisplayName = "默认游戏模式", Description = "新玩家首次进入的模式", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.difficulty", DisplayName = "难度", Description = "PEACEFUL=和平；HARD=困难，影响刷怪与饥饿", Category = "TODO", ValueType = "enum", DefaultValue = "NORMAL", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.gamemode", DisplayName = "默认游戏模式", Description = "新玩家首次进入的模式", Category = "TODO", ValueType = "enum", DefaultValue = "SURVIVAL", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.gamemode-force", DisplayName = "默认游戏模式", Description = "新玩家首次进入的模式", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.hardcore", DisplayName = "极限模式", Description = "死亡后封禁该玩家，难度自动锁定 HARD", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.max-build-height", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "int", DefaultValue = "256", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.pvp", DisplayName = "允许玩家 PvP", Description = "是否允许玩家间互相伤害", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.resource-pack", DisplayName = "资源包 URL", Description = "玩家进服时强制推送的资源包下载地址", Category = "TODO", ValueType = "string", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "game.resource-pack-hash", DisplayName = "资源包 URL", Description = "玩家进服时强制推送的资源包下载地址", Category = "TODO", ValueType = "string", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "libraries.checksum-validation", DisplayName = "检查库更新", Description = "启动时检查依赖库是否有新版本", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "libraries.compatibility-bundle", DisplayName = "检查库更新", Description = "启动时检查依赖库是否有新版本", Category = "TODO", ValueType = "string", DefaultValue = "CRAFTBUKKIT", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "libraries.download-attempts", DisplayName = "检查库更新", Description = "启动时检查依赖库是否有新版本", Category = "TODO", ValueType = "int", DefaultValue = "2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "libraries.list", DisplayName = "启用白名单", Description = "开启后只有 whitelist.json 中的玩家可进入", Category = "TODO", ValueType = "list", DefaultValue = "[]", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "libraries.repository-url", DisplayName = "检查库更新", Description = "启动时检查依赖库是否有新版本", Category = "TODO", ValueType = "string", DefaultValue = "https://repo.glowstone.net/repository/maven-public/", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.allow-client-mods", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.dns", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "list", DefaultValue = "[]", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.ip", DisplayName = "监听 IP", Description = "留空监听所有网卡；填入具体 IP 仅监听该网卡", Category = "TODO", ValueType = "string", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.log-file", DisplayName = "日志文件路径", Description = "主日志输出文件", Category = "TODO", ValueType = "string", DefaultValue = "logs/log-%D.txt", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.max-players", DisplayName = "最大玩家数", Description = "同时在线上限，超出的玩家进入排队或被踢", Category = "TODO", ValueType = "int", DefaultValue = "20", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.motd", DisplayName = "服务器描述", Description = "客户端服务器列表显示的文字，支持 § 颜色码", Category = "TODO", ValueType = "string", DefaultValue = "A Glowstone server", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.name", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "string", DefaultValue = "Glowstone Server", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.online-mode", DisplayName = "正版验证", Description = "true=只允许正版玩家；false=允许离线/盗版账号，注意皮肤与 UUID 会变", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.port", DisplayName = "服务器端口", Description = "客户端连接端口，0 表示随机端口", Category = "TODO", ValueType = "int", DefaultValue = "25565", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.prevent-proxy-connections", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.shutdown-message", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "string", DefaultValue = "Server shutting down.", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.snooper-enabled", DisplayName = "启用信息收集", Description = "上报匿名数据到 Mojang，强烈建议保持 false", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "server.whitelisted", DisplayName = "服务器名称", Description = "仅用于日志与部分插件识别，不影响客户端显示", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.allow-end", DisplayName = "允许飞行", Description = "非创造模式是否允许飞行（防作弊检测）", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.allow-nether", DisplayName = "允许飞行", Description = "非创造模式是否允许飞行（防作弊检测）", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.classic-style-water", DisplayName = "水生动物上限", Description = "单个世界水生动物数量上限", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.disable-generation", DisplayName = "主世界名称", Description = "主世界存档文件夹名", Category = "TODO", ValueType = "bool", DefaultValue = "False", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.gen-structures", DisplayName = "主世界名称", Description = "主世界存档文件夹名", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.keep-spawn-loaded", DisplayName = "保持出生加载", Description = "出生点区块常驻内存", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.level-type", DisplayName = "主世界名称", Description = "主世界存档文件夹名", Category = "TODO", ValueType = "enum", DefaultValue = "DEFAULT", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.name", DisplayName = "主世界名称", Description = "主世界存档文件夹名", Category = "TODO", ValueType = "enum", DefaultValue = "world", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.populate-anchored-chunks", DisplayName = "主世界名称", Description = "主世界存档文件夹名", Category = "TODO", ValueType = "bool", DefaultValue = "True", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.seed", DisplayName = "世界种子", Description = "留空随机生成；填入固定种子可复现世界", Category = "TODO", ValueType = "enum", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.spawn-radius", DisplayName = "出生点保护半径", Description = "出生点周围多少格内非 OP 无法破坏，0=关闭保护", Category = "TODO", ValueType = "int", DefaultValue = "16", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "glowstone.yml", Key = "world.view-distance", DisplayName = "视野距离", Description = "玩家周围加载区块半径，每 +1 增加约 15% 带宽消耗", Category = "TODO", ValueType = "int", DefaultValue = "8", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3

// ── worlds.yml (75 keys) ──
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "end.coordinate-scale", DisplayName = "启用末地", Description = "是否生成/加载末地维度", Category = "TODO", ValueType = "double", DefaultValue = "684.412", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "end.detail.noise-scale.x", DisplayName = "启用末地", Description = "是否生成/加载末地维度", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "end.detail.noise-scale.y", DisplayName = "启用末地", Description = "是否生成/加载末地维度", Category = "TODO", ValueType = "double", DefaultValue = "160.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "end.detail.noise-scale.z", DisplayName = "启用末地", Description = "是否生成/加载末地维度", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "end.height.scale", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "1368.824", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "general.sea_level", DisplayName = "数据包压缩级别", Description = "Netty Zlib 压缩级别。0=不压缩（最快、最费带宽）；9=最高压缩（最省带宽、最费 CPU）。推荐 6 平衡", Category = "TODO", ValueType = "int", DefaultValue = "64", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.coordinate-scale", DisplayName = "启用下界", Description = "是否生成/加载下界维度", Category = "TODO", ValueType = "double", DefaultValue = "684.412", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.detail.noise-scale.x", DisplayName = "启用下界", Description = "是否生成/加载下界维度", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.detail.noise-scale.y", DisplayName = "启用下界", Description = "是否生成/加载下界维度", Category = "TODO", ValueType = "double", DefaultValue = "60.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.detail.noise-scale.z", DisplayName = "启用下界", Description = "是否生成/加载下界维度", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.height.noise-scale.x", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "100.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.height.noise-scale.z", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "100.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.height.scale", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "2053.236", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=2
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "nether.surface-scale", DisplayName = "启用下界", Description = "是否生成/加载下界维度", Category = "TODO", ValueType = "double", DefaultValue = "0.0625", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.base-size", DisplayName = "书本单页最大字节", Description = "成书单页最大字节数。降低可防止恶意长 NBT 卡服。", Category = "TODO", ValueType = "double", DefaultValue = "8.5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height-offset", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height-weight", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "1.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.big-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.525", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.big-hills2", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.55", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.deep-ocean", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "-1.8", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.default", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.default-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.extreme-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "1.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.flat-shore", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.flatlands", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.125", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.flatlands-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.275", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.high-plateau", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "1.5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.high-spikes", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "1.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.45", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.low-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.low-spikes", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.4125", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.mid-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.3", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.mid-hills2", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.mid-plains", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.ocean", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "-1.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.river", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "-0.5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.rocky-shore", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.swampland", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "-0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.height.swampland-hills", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "-0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale-offset", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale-weight", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "1.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.big-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.55", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.big-hills2", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.deep-ocean", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.default", DisplayName = "默认方块范围", Description = "玩家在此范围内方块实体才 tick", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.default-hills", DisplayName = "默认方块范围", Description = "玩家在此范围内方块实体才 tick", Category = "TODO", ValueType = "double", DefaultValue = "0.4", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.extreme-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.5", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.flat-shore", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.025", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.flatlands", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.05", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.flatlands-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.25", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.high-plateau", DisplayName = "高速时异步传送", Description = "玩家高速移动（高速度）时使用异步传送。实验性，可能改善高速场景下的传送稳定性。", Category = "TODO", ValueType = "double", DefaultValue = "0.025", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.high-spikes", DisplayName = "高速时异步传送", Description = "玩家高速移动（高速度）时使用异步传送。实验性，可能改善高速场景下的传送稳定性。", Category = "TODO", ValueType = "double", DefaultValue = "1.3125", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.3", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.low-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.3", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.low-spikes", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "1.325", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.mid-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.4", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.mid-hills2", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.4", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.mid-plains", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.2", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.ocean", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.river", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.rocky-shore", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.8", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.swampland", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.1", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.biome.scale.swampland-hills", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.3", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.coordinate-scale", DisplayName = "修复坐标泄露漏洞", Description = "是否修复通过传送包反推远处坐标的漏洞。true=修复（推荐）；false=允许玩家通过特定客户端作弊获取远距离方块位置", Category = "TODO", ValueType = "double", DefaultValue = "684.412", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.density.fill.mode", DisplayName = "正版验证", Description = "true=只允许正版玩家；false=允许离线/盗版账号，注意皮肤与 UUID 会变", Category = "TODO", ValueType = "int", DefaultValue = "0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.density.fill.offset", DisplayName = "减少密度射线", Description = "减少爆炸密度射线计算量。true 可显著降低 TNT 大量爆炸时的 CPU 占用，但爆炸破坏精度略降。", Category = "TODO", ValueType = "double", DefaultValue = "0.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.density.fill.sea-mode", DisplayName = "正版验证", Description = "true=只允许正版玩家；false=允许离线/盗版账号，注意皮肤与 UUID 会变", Category = "TODO", ValueType = "int", DefaultValue = "0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.detail.noise-scale.x", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.detail.noise-scale.y", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "160.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.detail.noise-scale.z", DisplayName = "修复玩家 Z 闪烁", Description = "是否修复玩家在低 Y 高速移动时的 Z 轴闪烁问题。true=修复（推荐）；false=原版行为", Category = "TODO", ValueType = "double", DefaultValue = "80.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.height.noise-scale.x", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "200.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.height.noise-scale.z", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "200.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.height.scale", DisplayName = "最大建筑高度", Description = "玩家可放置方块的最大 Y 坐标", Category = "TODO", ValueType = "double", DefaultValue = "684.412", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=1
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.stretch-y", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "12.0", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0
new ServerConfigDescriptor { ConfigFileName = "worlds.yml", Key = "overworld.surface-scale", DisplayName = "TODO", Description = "TODO", Category = "TODO", ValueType = "double", DefaultValue = "0.0625", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=0

// ── commands.yml (1 keys) ──
new ServerConfigDescriptor { ConfigFileName = "commands.yml", Key = "aliases.icanhasbukkit", DisplayName = "命令别名", Description = "自定义命令别名映射", Category = "TODO", ValueType = "list", DefaultValue = "[\"version $1-\", \"plugins\"]", IntroducedIn = "2021.8.0" },  # [AUTO] rag_snippets=3

// ════════════════════════════════════════════════════
// SPOT-CHECK REPORT — 159 entries need human review
// Pick 20% random entries. Judge each against BAD/GOOD table in spec.
// ════════════════════════════════════════════════════

// [new_key] glowstone.yml :: advanced.compression-threshold
//   display_hint: 网络压缩阈值
//   default:      256

// [new_key] glowstone.yml :: advanced.connection-throttle
//   display_hint: 连接节流
//   default:      4000

// [new_key] glowstone.yml :: advanced.deprecated-verbose
//   display_hint: 连接节流
//   default:      false

// [new_key] glowstone.yml :: advanced.exact-login-location
//   display_hint: 精确登录位置
//   default:      False

// [new_key] glowstone.yml :: advanced.graphics-compute.enable
//   display_hint: 连接节流
//   default:      False

// [new_key] glowstone.yml :: advanced.graphics-compute.use-any-device
//   display_hint: 连接节流
//   default:      False

// [new_key] glowstone.yml :: advanced.idle-timeout
//   display_hint: 空闲超时
//   default:      0

// [new_key] glowstone.yml :: advanced.player-sample-count
//   display_hint: 连接节流
//   default:      12

// [new_key] glowstone.yml :: advanced.plugin-profiling
//   display_hint: 插件性能分析
//   default:      False

// [new_key] glowstone.yml :: advanced.profile-lookup-timeout
//   display_hint: 连接节流
//   default:      5

// [new_key] glowstone.yml :: advanced.proxy-support
//   display_hint: 拒绝代理连接
//   default:      False

// [new_key] glowstone.yml :: advanced.region-file.cache-size
//   display_hint: 日志文件路径
//   default:      256

// [new_key] glowstone.yml :: advanced.region-file.compression
//   display_hint: 日志文件路径
//   default:      True

// [new_key] glowstone.yml :: advanced.suggest-player-name-when-null-tab-completions
//   display_hint: 服务器名称
//   default:      True

// [new_key] glowstone.yml :: advanced.warn-on-overload
//   display_hint: 过载警告
//   default:      True

// [new_key] glowstone.yml :: console.date-format
//   display_hint: 日期格式
//   default:      HH:mm:ss

// [new_key] glowstone.yml :: console.log-date-format
//   display_hint: 日志文件路径
//   default:      yyyy/MM/dd HH:mm:ss

// [new_key] glowstone.yml :: console.prompt
//   display_hint: 资源包提示文本
//   default:      > 

// [new_key] glowstone.yml :: console.use-jline
//   display_hint: 启用命令历史
//   default:      True

// [new_key] glowstone.yml :: creatures.enable.animals
//   display_hint: 生成怪物
//   default:      True

// [new_key] glowstone.yml :: creatures.enable.monsters
//   display_hint: 生成怪物
//   default:      True

// [new_key] glowstone.yml :: creatures.enable.npcs
//   display_hint: 生成怪物
//   default:      True

// [new_key] glowstone.yml :: creatures.limit.ambient
//   display_hint: 生成怪物
//   default:      15

// [new_key] glowstone.yml :: creatures.limit.animals
//   display_hint: 生成怪物
//   default:      15

// [new_key] glowstone.yml :: creatures.limit.monsters
//   display_hint: 生成怪物
//   default:      70

// [new_key] glowstone.yml :: creatures.limit.water
//   display_hint: 生成怪物
//   default:      5

// [new_key] glowstone.yml :: creatures.ticks.animal
//   display_hint: 生成怪物
//   default:      400

// [new_key] glowstone.yml :: creatures.ticks.monsters
//   display_hint: 生成怪物
//   default:      1

// [new_key] glowstone.yml :: extras.query-enabled
//   display_hint: 启用信息收集
//   default:      False

// [new_key] glowstone.yml :: extras.query-plugins
//   display_hint: 插件目录
//   default:      True

// [new_key] glowstone.yml :: extras.query-port
//   display_hint: 服务器端口
//   default:      25614

// [new_key] glowstone.yml :: extras.rcon-colors
//   display_hint: 控制台彩色输出
//   default:      True

// [new_key] glowstone.yml :: extras.rcon-enabled
//   display_hint: 启用信息收集
//   default:      False

// [new_key] glowstone.yml :: extras.rcon-password
//   display_hint: 显示 TPS
//   default:      glowstone

// [new_key] glowstone.yml :: extras.rcon-port
//   display_hint: 服务器端口
//   default:      25575

// [new_key] glowstone.yml :: files.commands
//   display_hint: 命令文件
//   default:      commands.yml

// [new_key] glowstone.yml :: files.help
//   display_hint: 帮助文件
//   default:      help.yml

// [new_key] glowstone.yml :: files.permissions
//   display_hint: 权限文件
//   default:      permissions.yml

// [new_key] glowstone.yml :: folders.libraries
//   display_hint: 配置目录
//   default:      lib

// [new_key] glowstone.yml :: folders.plugins
//   display_hint: 插件目录
//   default:      plugins

// [new_key] glowstone.yml :: folders.update
//   display_hint: 配置目录
//   default:      update

// [new_key] glowstone.yml :: folders.worlds
//   display_hint: 世界目录
//   default:      worlds

// [new_key] glowstone.yml :: game.allow-flight
//   display_hint: 允许飞行
//   default:      False

// [new_key] glowstone.yml :: game.announce-achievements
//   display_hint: 公告成就
//   default:      True

// [new_key] glowstone.yml :: game.command-blocks
//   display_hint: 默认游戏模式
//   default:      False

// [new_key] glowstone.yml :: game.difficulty
//   display_hint: 难度
//   default:      NORMAL

// [new_key] glowstone.yml :: game.gamemode
//   display_hint: 默认游戏模式
//   default:      SURVIVAL

// [new_key] glowstone.yml :: game.gamemode-force
//   display_hint: 默认游戏模式
//   default:      False

// [new_key] glowstone.yml :: game.hardcore
//   display_hint: 极限模式
//   default:      False

// [new_key] glowstone.yml :: game.max-build-height
//   display_hint: 最大建筑高度
//   default:      256

// [new_key] glowstone.yml :: game.pvp
//   display_hint: 允许玩家 PvP
//   default:      True

// [new_key] glowstone.yml :: game.resource-pack
//   display_hint: 资源包 URL
//   default:      

// [new_key] glowstone.yml :: game.resource-pack-hash
//   display_hint: 资源包 URL
//   default:      

// [new_key] glowstone.yml :: libraries.checksum-validation
//   display_hint: 检查库更新
//   default:      True

// [new_key] glowstone.yml :: libraries.compatibility-bundle
//   display_hint: 检查库更新
//   default:      CRAFTBUKKIT

// [new_key] glowstone.yml :: libraries.download-attempts
//   display_hint: 检查库更新
//   default:      2

// [new_key] glowstone.yml :: libraries.list
//   display_hint: 启用白名单
//   default:      []

// [new_key] glowstone.yml :: libraries.repository-url
//   display_hint: 检查库更新
//   default:      https://repo.glowstone.net/repository/maven-public/

// [new_key] glowstone.yml :: server.allow-client-mods
//   display_hint: 服务器名称
//   default:      True

// [new_key] glowstone.yml :: server.dns
//   display_hint: 服务器名称
//   default:      []

// [new_key] glowstone.yml :: server.ip
//   display_hint: 监听 IP
//   default:      

// [new_key] glowstone.yml :: server.log-file
//   display_hint: 日志文件路径
//   default:      logs/log-%D.txt

// [new_key] glowstone.yml :: server.max-players
//   display_hint: 最大玩家数
//   default:      20

// [new_key] glowstone.yml :: server.motd
//   display_hint: 服务器描述
//   default:      A Glowstone server

// [new_key] glowstone.yml :: server.name
//   display_hint: 服务器名称
//   default:      Glowstone Server

// [new_key] glowstone.yml :: server.online-mode
//   display_hint: 正版验证
//   default:      True

// [new_key] glowstone.yml :: server.port
//   display_hint: 服务器端口
//   default:      25565

// [new_key] glowstone.yml :: server.prevent-proxy-connections
//   display_hint: 服务器名称
//   default:      True

// [new_key] glowstone.yml :: server.shutdown-message
//   display_hint: 服务器名称
//   default:      Server shutting down.

// [new_key] glowstone.yml :: server.snooper-enabled
//   display_hint: 启用信息收集
//   default:      False

// [new_key] glowstone.yml :: server.whitelisted
//   display_hint: 服务器名称
//   default:      False

// [new_key] glowstone.yml :: world.allow-end
//   display_hint: 允许飞行
//   default:      True

// [new_key] glowstone.yml :: world.allow-nether
//   display_hint: 允许飞行
//   default:      True

// [new_key] glowstone.yml :: world.classic-style-water
//   display_hint: 水生动物上限
//   default:      False

// [new_key] glowstone.yml :: world.disable-generation
//   display_hint: 主世界名称
//   default:      False

// [new_key] glowstone.yml :: world.gen-structures
//   display_hint: 主世界名称
//   default:      True

// [new_key] glowstone.yml :: world.keep-spawn-loaded
//   display_hint: 保持出生加载
//   default:      True

// [new_key] glowstone.yml :: world.level-type
//   display_hint: 主世界名称
//   default:      DEFAULT

// [new_key] glowstone.yml :: world.name
//   display_hint: 主世界名称
//   default:      world

// [new_key] glowstone.yml :: world.populate-anchored-chunks
//   display_hint: 主世界名称
//   default:      True

// [new_key] glowstone.yml :: world.seed
//   display_hint: 世界种子
//   default:      

// [new_key] glowstone.yml :: world.spawn-radius
//   display_hint: 出生点保护半径
//   default:      16

// [new_key] glowstone.yml :: world.view-distance
//   display_hint: 视野距离
//   default:      8

// [new_key] worlds.yml :: end.coordinate-scale
//   display_hint: 启用末地
//   default:      684.412

// [new_key] worlds.yml :: end.detail.noise-scale.x
//   display_hint: 启用末地
//   default:      80.0

// [new_key] worlds.yml :: end.detail.noise-scale.y
//   display_hint: 启用末地
//   default:      160.0

// [new_key] worlds.yml :: end.detail.noise-scale.z
//   display_hint: 启用末地
//   default:      80.0

// [new_key] worlds.yml :: end.height.scale
//   display_hint: 最大建筑高度
//   default:      1368.824

// [new_key] worlds.yml :: general.sea_level
//   display_hint: 数据包压缩级别
//   default:      64

// [new_key] worlds.yml :: nether.coordinate-scale
//   display_hint: 启用下界
//   default:      684.412

// [new_key] worlds.yml :: nether.detail.noise-scale.x
//   display_hint: 启用下界
//   default:      80.0

// [new_key] worlds.yml :: nether.detail.noise-scale.y
//   display_hint: 启用下界
//   default:      60.0

// [new_key] worlds.yml :: nether.detail.noise-scale.z
//   display_hint: 启用下界
//   default:      80.0

// [new_key] worlds.yml :: nether.height.noise-scale.x
//   display_hint: 最大建筑高度
//   default:      100.0

// [new_key] worlds.yml :: nether.height.noise-scale.z
//   display_hint: 最大建筑高度
//   default:      100.0

// [new_key] worlds.yml :: nether.height.scale
//   display_hint: 最大建筑高度
//   default:      2053.236

// [new_key] worlds.yml :: nether.surface-scale
//   display_hint: 启用下界
//   default:      0.0625

// [new_key] worlds.yml :: overworld.base-size
//   display_hint: 书本单页最大字节
//   default:      8.5

// [new_key] worlds.yml :: overworld.biome.height-offset
//   display_hint: 最大建筑高度
//   default:      0.0

// [new_key] worlds.yml :: overworld.biome.height-weight
//   display_hint: 最大建筑高度
//   default:      1.0

// [new_key] worlds.yml :: overworld.biome.height.big-hills
//   display_hint: 最大建筑高度
//   default:      0.525

// [new_key] worlds.yml :: overworld.biome.height.big-hills2
//   display_hint: 最大建筑高度
//   default:      0.55

// [new_key] worlds.yml :: overworld.biome.height.deep-ocean
//   display_hint: 最大建筑高度
//   default:      -1.8

// [new_key] worlds.yml :: overworld.biome.height.default
//   display_hint: 最大建筑高度
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.height.default-hills
//   display_hint: 最大建筑高度
//   default:      0.2

// [new_key] worlds.yml :: overworld.biome.height.extreme-hills
//   display_hint: 最大建筑高度
//   default:      1.0

// [new_key] worlds.yml :: overworld.biome.height.flat-shore
//   display_hint: 最大建筑高度
//   default:      0.0

// [new_key] worlds.yml :: overworld.biome.height.flatlands
//   display_hint: 最大建筑高度
//   default:      0.125

// [new_key] worlds.yml :: overworld.biome.height.flatlands-hills
//   display_hint: 最大建筑高度
//   default:      0.275

// [new_key] worlds.yml :: overworld.biome.height.high-plateau
//   display_hint: 最大建筑高度
//   default:      1.5

// [new_key] worlds.yml :: overworld.biome.height.high-spikes
//   display_hint: 最大建筑高度
//   default:      1.1

// [new_key] worlds.yml :: overworld.biome.height.hills
//   display_hint: 最大建筑高度
//   default:      0.45

// [new_key] worlds.yml :: overworld.biome.height.low-hills
//   display_hint: 最大建筑高度
//   default:      0.2

// [new_key] worlds.yml :: overworld.biome.height.low-spikes
//   display_hint: 最大建筑高度
//   default:      0.4125

// [new_key] worlds.yml :: overworld.biome.height.mid-hills
//   display_hint: 最大建筑高度
//   default:      0.3

// [new_key] worlds.yml :: overworld.biome.height.mid-hills2
//   display_hint: 最大建筑高度
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.height.mid-plains
//   display_hint: 最大建筑高度
//   default:      0.2

// [new_key] worlds.yml :: overworld.biome.height.ocean
//   display_hint: 最大建筑高度
//   default:      -1.0

// [new_key] worlds.yml :: overworld.biome.height.river
//   display_hint: 最大建筑高度
//   default:      -0.5

// [new_key] worlds.yml :: overworld.biome.height.rocky-shore
//   display_hint: 最大建筑高度
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.height.swampland
//   display_hint: 最大建筑高度
//   default:      -0.2

// [new_key] worlds.yml :: overworld.biome.height.swampland-hills
//   display_hint: 最大建筑高度
//   default:      -0.1

// [new_key] worlds.yml :: overworld.biome.scale-offset
//   display_hint: (no RAG hit)
//   default:      0.0

// [new_key] worlds.yml :: overworld.biome.scale-weight
//   display_hint: (no RAG hit)
//   default:      1.0

// [new_key] worlds.yml :: overworld.biome.scale.big-hills
//   display_hint: (no RAG hit)
//   default:      0.55

// [new_key] worlds.yml :: overworld.biome.scale.big-hills2
//   display_hint: (no RAG hit)
//   default:      0.5

// [new_key] worlds.yml :: overworld.biome.scale.deep-ocean
//   display_hint: (no RAG hit)
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.scale.default
//   display_hint: 默认方块范围
//   default:      0.2

// [new_key] worlds.yml :: overworld.biome.scale.default-hills
//   display_hint: 默认方块范围
//   default:      0.4

// [new_key] worlds.yml :: overworld.biome.scale.extreme-hills
//   display_hint: (no RAG hit)
//   default:      0.5

// [new_key] worlds.yml :: overworld.biome.scale.flat-shore
//   display_hint: (no RAG hit)
//   default:      0.025

// [new_key] worlds.yml :: overworld.biome.scale.flatlands
//   display_hint: (no RAG hit)
//   default:      0.05

// [new_key] worlds.yml :: overworld.biome.scale.flatlands-hills
//   display_hint: (no RAG hit)
//   default:      0.25

// [new_key] worlds.yml :: overworld.biome.scale.high-plateau
//   display_hint: 高速时异步传送
//   default:      0.025

// [new_key] worlds.yml :: overworld.biome.scale.high-spikes
//   display_hint: 高速时异步传送
//   default:      1.3125

// [new_key] worlds.yml :: overworld.biome.scale.hills
//   display_hint: (no RAG hit)
//   default:      0.3

// [new_key] worlds.yml :: overworld.biome.scale.low-hills
//   display_hint: (no RAG hit)
//   default:      0.3

// [new_key] worlds.yml :: overworld.biome.scale.low-spikes
//   display_hint: (no RAG hit)
//   default:      1.325

// [new_key] worlds.yml :: overworld.biome.scale.mid-hills
//   display_hint: (no RAG hit)
//   default:      0.4

// [new_key] worlds.yml :: overworld.biome.scale.mid-hills2
//   display_hint: (no RAG hit)
//   default:      0.4

// [new_key] worlds.yml :: overworld.biome.scale.mid-plains
//   display_hint: (no RAG hit)
//   default:      0.2

// [new_key] worlds.yml :: overworld.biome.scale.ocean
//   display_hint: (no RAG hit)
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.scale.river
//   display_hint: (no RAG hit)
//   default:      0.0

// [new_key] worlds.yml :: overworld.biome.scale.rocky-shore
//   display_hint: (no RAG hit)
//   default:      0.8

// [new_key] worlds.yml :: overworld.biome.scale.swampland
//   display_hint: (no RAG hit)
//   default:      0.1

// [new_key] worlds.yml :: overworld.biome.scale.swampland-hills
//   display_hint: (no RAG hit)
//   default:      0.3

// [new_key] worlds.yml :: overworld.coordinate-scale
//   display_hint: 修复坐标泄露漏洞
//   default:      684.412

// [new_key] worlds.yml :: overworld.density.fill.mode
//   display_hint: 正版验证
//   default:      0

// [new_key] worlds.yml :: overworld.density.fill.offset
//   display_hint: 减少密度射线
//   default:      0.0

// [new_key] worlds.yml :: overworld.density.fill.sea-mode
//   display_hint: 正版验证
//   default:      0

// [new_key] worlds.yml :: overworld.detail.noise-scale.x
//   display_hint: (no RAG hit)
//   default:      80.0

// [new_key] worlds.yml :: overworld.detail.noise-scale.y
//   display_hint: (no RAG hit)
//   default:      160.0

// [new_key] worlds.yml :: overworld.detail.noise-scale.z
//   display_hint: 修复玩家 Z 闪烁
//   default:      80.0

// [new_key] worlds.yml :: overworld.height.noise-scale.x
//   display_hint: 最大建筑高度
//   default:      200.0

// [new_key] worlds.yml :: overworld.height.noise-scale.z
//   display_hint: 最大建筑高度
//   default:      200.0

// [new_key] worlds.yml :: overworld.height.scale
//   display_hint: 最大建筑高度
//   default:      684.412

// [new_key] worlds.yml :: overworld.stretch-y
//   display_hint: (no RAG hit)
//   default:      12.0

// [new_key] worlds.yml :: overworld.surface-scale
//   display_hint: (no RAG hit)
//   default:      0.0625

// [new_key] commands.yml :: aliases.icanhasbukkit
//   display_hint: 命令别名
//   default:      ["version $1-", "plugins"]
